

// seed.js
const mongoose = require('mongoose');
const Event = require('./models/Event');

const events = [
    {
        name: "TechFest 2025",
        image: "https://example.com/images/techfest.jpg",
        date: new Date("2025-08-10"),
        time: "10:00 AM",
        content: "A grand celebration of technology, innovation, and talent.",
        location: "GLA University, Mathura",
        organizer: "GLA CSE Dept",
        price: 0,
        status: "upcoming",
    },
    {
        name: "Startup Pitch Night",
        image: "https://example.com/images/pitchnight.jpg",
        date: new Date("2025-07-15"),
        time: "06:00 PM",
        content: "Young entrepreneurs pitch their startups to investors.",
        location: "Nepal Tech Park, Kathmandu",
        organizer: "Nepal Startup Foundation",
        price: 200,
        status: "upcoming",
    },
    {
        name: "AI Conference",
        image: "https://example.com/images/aiconf.jpg",
        date: new Date("2025-07-01"),
        time: "09:30 AM",
        content: "Talks and workshops on Artificial Intelligence and ML.",
        location: "Bangalore International Centre",
        organizer: "AI Global",
        price: 1500,
        status: "completed",
    },
    {
        name: "Hackathon 5.0",
        image: "https://example.com/images/hackathon.jpg",
        date: new Date("2025-09-20"),
        time: "12:00 PM",
        content: "24-hour coding challenge with exciting prizes.",
        location: "Hyderabad Tech City",
        organizer: "CodeCraft",
        price: 100,
        status: "upcoming",
    },
    {
        name: "DevCon India",
        image: "https://example.com/images/devcon.jpg",
        date: new Date("2025-08-22"),
        time: "11:00 AM",
        content: "Developer community meetup with talks and networking.",
        location: "Chennai Convention Centre",
        organizer: "DevGuild",
        price: 350,
        status: "upcoming",
    },
    {
        name: "Flutter Workshop",
        image: "https://example.com/images/flutter.jpg",
        date: new Date("2025-07-02"),
        time: "03:00 PM",
        content: "Hands-on workshop on Flutter app development.",
        location: "Online",
        organizer: "Flutter Nepal",
        price: 50,
        status: "completed",
    },
    {
        name: "Cybersecurity Bootcamp",
        image: "https://example.com/images/cyber.jpg",
        date: new Date("2025-06-28"),
        time: "10:00 AM",
        content: "Learn about ethical hacking and online security.",
        location: "Pune Cyber Hub",
        organizer: "CyberSafe",
        price: 750,
        status: "expired",
    },
    {
        name: "Game Development Jam",
        image: "https://example.com/images/gamedev.jpg",
        date: new Date("2025-08-01"),
        time: "02:00 PM",
        content: "Collaborative event to build indie games in 2 days.",
        location: "Indore Game Studio",
        organizer: "IndieDev",
        price: 100,
        status: "upcoming",
    },
    {
        name: "UX/UI Design Sprint",
        image: "https://example.com/images/uxui.jpg",
        date: new Date("2025-07-18"),
        time: "01:00 PM",
        content: "Designing intuitive and user-centric experiences.",
        location: "Design District, Noida",
        organizer: "UX India",
        price: 200,
        status: "upcoming",
    },
    {
        name: "Robotics Expo",
        image: "https://example.com/images/robotics.jpg",
        date: new Date("2025-10-01"),
        time: "09:00 AM",
        content: "Live demos of next-gen robots and tech.",
        location: "Ahmedabad Tech Center",
        organizer: "RoboTech",
        price: 500,
        status: "upcoming",
    },
    {
        name: "Blockchain Summit",
        image: "https://example.com/images/blockchain.jpg",
        date: new Date("2025-06-10"),
        time: "11:00 AM",
        content: "Everything about cryptocurrency and blockchain.",
        location: "Mumbai FinTech Valley",
        organizer: "CryptoNepal",
        price: 600,
        status: "expired",
    },
    {
        name: "Python Bootcamp",
        image: "https://example.com/images/python.jpg",
        date: new Date("2025-07-20"),
        time: "04:00 PM",
        content: "Beginner to advanced level Python programming bootcamp.",
        location: "Online",
        organizer: "PyAcademy",
        price: 250,
        status: "upcoming",
    },
    {
        name: "Open Source Day",
        image: "https://example.com/images/opensource.jpg",
        date: new Date("2025-09-05"),
        time: "10:00 AM",
        content: "Celebration and contribution to open-source projects.",
        location: "Remote/Online",
        organizer: "GitHub India",
        price: 0,
        status: "upcoming",
    },
    {
        name: "Mobile App Demo Day",
        image: "https://example.com/images/appdemo.jpg",
        date: new Date("2025-06-30"),
        time: "02:00 PM",
        content: "Showcase your mobile apps to mentors and peers.",
        location: "Delhi Technopark",
        organizer: "AppMinds",
        price: 120,
        status: "expired",
    },
    {
        name: "Designathon",
        image: "https://example.com/images/designathon.jpg",
        date: new Date("2025-08-25"),
        time: "10:00 AM",
        content: "Creative design sprint competition for UI/UX designers.",
        location: "Surat Innovation Lab",
        organizer: "DesignGeeks",
        price: 300,
        status: "upcoming",
    },
    {
        name: "Career Fair 2025",
        image: "https://example.com/images/careerfair.jpg",
        date: new Date("2025-07-25"),
        time: "09:00 AM",
        content: "Connect with companies for internship and job opportunities.",
        location: "Lucknow Career Expo Hall",
        organizer: "GLA T&P Cell",
        price: 0,
        status: "upcoming",
    },
    {
        name: "Neural Networks Deep Dive",
        image: "https://example.com/images/neural.jpg",
        date: new Date("2025-06-20"),
        time: "03:00 PM",
        content: "Deep learning theory and implementation of neural networks.",
        location: "IIT Kanpur",
        organizer: "DeepLearning.AI",
        price: 1000,
        status: "expired",
    },
    {
        name: "Women in Tech Meetup",
        image: "https://example.com/images/womenintech.jpg",
        date: new Date("2025-09-10"),
        time: "05:00 PM",
        content: "Empowering women in the tech industry through stories and support.",
        location: "Nepal WomenTech Center",
        organizer: "SheCodes Nepal",
        price: 0,
        status: "upcoming",
    },
    {
        name: "Cloud Computing Workshop",
        image: "https://example.com/images/cloud.jpg",
        date: new Date("2025-07-09"),
        time: "01:00 PM",
        content: "Learn cloud services like AWS, Azure, and GCP.",
        location: "Remote/Online",
        organizer: "CloudForce",
        price: 400,
        status: "upcoming",
    },
    {
        name: "AR/VR Reality Show",
        image: "https://example.com/images/arvr.jpg",
        date: new Date("2025-10-15"),
        time: "03:30 PM",
        content: "Experience augmented and virtual reality in action.",
        location: "Delhi Immersive Lab",
        organizer: "XR India",
        price: 900,
        status: "upcoming",
    },
];

async function seedOnce() {
    try {
        const count = await Event.countDocuments();
        if (count === 0) {
            await Event.insertMany(events);
            console.log('🌱 Events seeded successfully.');
        } else {
            console.log('ℹ️ Events already exist. Skipping seed.');
        }
    } catch (err) {
        console.error('❌ Seeding error:', err);
    }
}

module.exports = seedOnce;
